### ISSUE TITLE
recurring no context problem

### ISSUE THREAD

**Issue by tveimo** [lifus/wro4j-runtime-taglib#4]
I sporadically get these, am thinking it might be a timing issue, since a page reload often results in a properly rendered page;

ro.isdc.wro.WroRuntimeException: No context associated with CURRENT request cycle!
    at ro.isdc.wro.config.Context.validateContext(Context.java:124)
    at ro.isdc.wro.config.Context.get(Context.java:107)
    at ro.isdc.wro.model.group.processor.InjectorBuilder$17.create(InjectorBuilder.java:254)
    at ro.isdc.wro.model.group.processor.InjectorBuilder$17.create(InjectorBuilder.java:252)
    at ro.isdc.wro.util.ProxyFactory$1.invoke(ProxyFactory.java:70)
    at com.sun.proxy.$Proxy356.getConfig(Unknown Source)
    at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.getResourceWatcherUpdatePeriod(DefaultSynchronizedCacheStrategyDecorator.java:109)
    at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.shouldWatchForChange(DefaultSynchronizedCacheStrategyDecorator.java:154)
    at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.onBeforeGet(DefaultSynchronizedCacheStrategyDecorator.java:142)
    at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.onBeforeGet(DefaultSynchronizedCacheStrategyDecorator.java:35)
    at ro.isdc.wro.cache.support.AbstractSynchronizedCacheStrategyDecorator.get(AbstractSynchronizedCacheStrategyDecorator.java:40)
    at com.github.lifus.wro4j_runtime_taglib.model.group.name.DefaultVersionedGroupNameFactory.getInputStream(DefaultVersionedGroupNameFactory.java:58)
    at com.github.lifus.wro4j_runtime_taglib.model.group.name.DefaultVersionedGroupNameFactory.create(DefaultVersionedGroupNameFactory.java:40)
    at com.github.lifus.wro4j_runtime_taglib.model.resource.uri.strategy.VersionedResourceUriStrategy.getPathRelativeToWroRoot(VersionedResourceUriStrategy.java:62)
    at com.github.lifus.wro4j_runtime_taglib.model.resource.uri.strategy.VersionedResourceUriStrategy.getUriOfOptimizedResource(VersionedResourceUriStrategy.java:49)
    at com.github.lifus.wro4j_runtime_taglib.model.resource.uri.strategy.VersionedResourceUriStrategy.getResourcesUris(VersionedResourceUriStrategy.java:45)
    at com.github.lifus.wro4j_runtime_taglib.model.resource.uri.strategy.ConfigurableResourceUriStrategy.getResourcesUris(ConfigurableResourceUriStrategy.java:110)
    at com.github.lifus.wro4j_runtime_taglib.model.resource.uri.cache.ResourceUriCacheStrategyDecorator.loadValue(ResourceUriCacheStrategyDecorator.java:38)
    at com.github.lifus.wro4j_runtime_taglib.model.resource.uri.cache.ResourceUriCacheStrategyDecorator.loadValue(ResourceUriCacheStrategyDecorator.java:17)
    at ro.isdc.wro.cache.support.AbstractSynchronizedCacheStrategyDecorator.get(AbstractSynchronizedCacheStrategyDecorator.java:55)
    at com.github.lifus.wro4j_runtime_taglib.context.TaglibContext.getResourceUris(TaglibContext.java:64)
    at com.github.lifus.wro4j_runtime_taglib.tag.AbstractWroElementTag.getResourceUris(AbstractWroElementTag.java:50)
    at com.github.lifus.wro4j_runtime_taglib.tag.AbstractWroElementTag.getOutput(AbstractWroElementTag.java:42)
    at com.github.lifus.wro4j_runtime_taglib.tag.AbstractHtmlElementTag.doTag(AbstractHtmlElementTag.java:23)

My filter mapping order is the following;

```
<filter-mapping>
    <filter-name>WroContextFilter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
<filter-mapping>
    <filter-name>springSecurityFilterChain</filter-name>
    <url-pattern>/*</url-pattern>
    <dispatcher>ERROR</dispatcher>
    <dispatcher>REQUEST</dispatcher>
</filter-mapping>
<filter-mapping>
    <filter-name>isUserInRoleFilter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
<filter-mapping>
    <filter-name>CharacterEncodingFilter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
<filter-mapping>
    <filter-name>WroFilter</filter-name>
    <url-pattern>/resources/wro/*</url-pattern>
    <url-pattern>/admin/wro/*</url-pattern>
</filter-mapping>

<filter-mapping>
    <filter-name>siteMeshFilter</filter-name>
    <url-pattern>/*</url-pattern>
    <dispatcher>FORWARD</dispatcher>
    <dispatcher>REQUEST</dispatcher>
    <dispatcher>ERROR</dispatcher>
</filter-mapping>

<filter-mapping>
    <filter-name>httpMethodFilter</filter-name>
    <servlet-name>appServlet</servlet-name>
</filter-mapping>
<filter-mapping>
    <filter-name>sessionRegisterFilter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
<filter-mapping>
    <filter-name>pageViewCounter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
```

**Comment by lifus** [comment]
This might be due to sitemesh filter mapping
My first guess is to add dispatchers e.g.

``` xml
<filter-mapping>
    <filter-name>WroContextFilter</filter-name>
    <url-pattern>/*</url-pattern>
    <dispatcher>FORWARD</dispatcher>
    <dispatcher>REQUEST</dispatcher>
    <dispatcher>ERROR</dispatcher>
</filter-mapping>
```

**Comment by lifus** [comment]
Did you experience this issue again?
Anyway, I'm certain that this issue is not related to taglib itself, but to certain WroContextFilter configuration. Here's a [similar thread](https://groups.google.com/forum/#!topic/wro4j/dQf4vnN5Zhg).
I'm closing it for now, but feel free to reopen it if you still encounter the same issue.

**Comment by tveimo** [comment]
I haven't experienced this again after correcting the dispatcher configuration.
